import { fmtDuration, tail } from '../util.js';

const CLASS_LABEL = {
  'runtime-version': 'Wrong runtime version', 'missing-script': 'Renamed or missing script', 'missing-env': 'Undocumented environment variable',
  'missing-service': 'Undocumented backing service', 'missing-tool': 'Missing tool', 'missing-dependency': 'Missing dependency',
  'wrong-order': 'Missing or out-of-order step', 'missing-file': 'Stale file reference', 'platform-specific': 'Platform-specific step',
  'needs-secret': 'Needs a real credential', unknown: 'Unrecognised failure',
};

export function classLabel(c) { return CLASS_LABEL[c] || c; }

/** FIRSTRUN.md: the human-readable Setup Passport with every evidence record. */
export function renderReport({ passport: p, plan, evidence, firstFailure, conflicts }) {
  const L = [];
  const icon = p.verdict === 'VERIFIED' ? '✅' : p.verdict === 'PARTIAL' ? '🟡' : '❌';
  L.push(`# Setup Passport: ${p.repo}`, '');
  L.push(`${icon} **${p.verdict}**: FirstRun followed this project's setup docs on a clean \`${p.image}\` machine, repaired what broke, then replayed the corrected guide from zero.`, '');
  L.push('| | |', '|---|---|');
  L.push(`| Commit | \`${p.commit}\` |`);
  L.push(`| Verified | ${p.verifiedAt.replace('T', ' ').slice(0, 16)} UTC |`);
  L.push(`| Runtime | ${p.runtime} (\`${p.image}\`) |`);
  L.push(`| Clone to running, from zero | **${p.replaySeconds ? fmtDuration(p.replaySeconds * 1000) : 'n/a'}** |`);
  L.push(`| Steps followed | ${p.stepsFromReadme} from the docs, ${p.stepsTotal - p.stepsFromReadme} added by FirstRun |`);
  L.push(`| Breaks found / fixed | ${p.breaksFound} / ${p.breaksFixed} |`);
  L.push(`| Needs a human | ${p.needsHuman} |`);
  L.push(`| Done when | ${p.verify.kind === 'http' ? `\`GET ${p.verify.target}\` answers` : p.verify.kind === 'command' ? `\`${p.verify.target}\` passes` : 'every step exits cleanly'} |`);
  if (p.bobcoins || p.diagnosedByBob) L.push(`| IBM Bob | ${p.diagnosedByBob} diagnosis${p.diagnosedByBob === 1 ? '' : 'es'}, ${p.bobcoins} Bobcoins |`);
  L.push('');
  if (firstFailure) {
    L.push(`**Before FirstRun**, a newcomer following the docs got stuck at \`${firstFailure.command}\` (${firstFailure.source.file}:${firstFailure.source.line}).`, '');
  }

  L.push('## Verified setup', '', '```bash');
  for (const s of plan.steps) {
    if (s.skip || s.status === 'needs-human') continue;
    L.push(s.command);
  }
  L.push('```', '');

  if (evidence.length) {
    L.push('## Evidence', '', 'Every change to the docs is backed by a command that failed before the fix and passed after it.', '');
    for (const e of evidence) {
      const step = plan.steps.find((s) => s.id === e.stepId);
      L.push(`### ${e.id}: ${classLabel(e.diagnosis.class)} <a id="${e.id.toLowerCase()}"></a>`, '');
      L.push(`- **Docs said:** \`${step?.readmeCommand || e.before.command}\` (${step?.source.file}:${step?.source.line})`);
      L.push(`- **Cause:** ${e.diagnosis.cause}`);
      L.push(`- **Diagnosed by:** ${e.diagnosis.by === 'bob' ? `IBM Bob (${e.diagnosis.bobcoins ?? 0} Bobcoins)` : `FirstRun rule \`${e.diagnosis.ruleId}\``}, confidence ${Math.round((e.diagnosis.confidence || 0) * 100)}%`);
      if (e.fix?.doc) L.push(`- **Doc change:** ${e.fix.doc.text}`);
      L.push(`- **Result:** ${e.status === 'verified' ? 'fixed and verified' : e.status === 'needs-human' ? 'needs a maintainer' : e.status === 'progressed' ? `worked: cleared this error, then the step failed on a later problem${e.revealed ? ` ([${e.revealed}](#${e.revealed.toLowerCase()}))` : ''}` : 'fix did not work'}`, '');
      L.push('<details><summary>Before (failing output)</summary>', '', '```', tail(e.before.logTail, 14), '```', '</details>', '');
      if (e.fix?.log) L.push('<details><summary>Fix applied</summary>', '', '```', tail(e.fix.log, 14), '```', '</details>', '');
      if (e.after) L.push('<details><summary>After (passing output)</summary>', '', '```', tail(e.after.logTail, 10), '```', '</details>', '');
    }
  }

  if (conflicts?.length) {
    L.push('## Docs vs. code', '', 'Found by reading the docs next to the manifests, compose file, CI and source:', '');
    L.push('| What | Docs say | Code says | Where |', '|---|---|---|---|');
    for (const c of conflicts) L.push(`| ${c.what} | ${c.docs} | ${c.truth} | ${c.source} |`);
    L.push('');
  }

  L.push('## Keeping it true', '', 'The workflow in `.github/workflows/firstrun.yml` re-checks setup on every pull request that touches the README, manifests, env files or compose files, and comments when a change would break a newcomer\'s first run.', '');
  L.push('Newcomers using IBM Bob can switch to the **FirstRun Guide** mode (`.bob/custom_modes.yaml`), which walks them through this verified setup one step at a time and recognises the known failure signatures above.', '');
  L.push('---', `Generated by FirstRun. Verified plan: \`.github/firstrun/plan.json\`.`);
  return L.join('\n') + '\n';
}
