services:
  app:
    image: node:22
    command: sleep infinity
    volumes:
      - ..:/workspace:cached
  db:
    image: postgres:18
    network_mode: service:app
    restart: unless-stopped
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:?Variable not set}
      POSTGRES_DB: app
